spring:
  application:
    name: sample-batch

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:h2:mem:sample_batch
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    org.springframework.batch: INFO